version: "2"
services:

  # Collector
  otel-collector:
    image: otel/opentelemetry-collector
    restart: always
    #command: ["--config=./otel-collector-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - "C:\\repos\\_try_otel\\otel-local-config.yaml:/otel-collector-config.yaml"
    ports:
      #- "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      #- "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      #- "55679:55679" # zpages extension
    #depends_on:
    #  - jaeger-all-in-one
    #  - zipkin-all-in-one

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    volumes:
      - "C:\\repos\\_try_otel\\prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"