version: "2"
services:

  # Collector
  otel-collector:
    image: otel/opentelemetry-collector
    restart: always
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - "C:\\repos\\_try_otel\\otel-local-config.yaml:/etc/otel-collector-config.yaml"
    ports:
      # - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      #- "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    volumes:
      - "C:\\repos\\_try_otel\\prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"