receivers:
  otlp:
    protocols:
      grpc:

exporters:
  logging:
    loglevel: debug
  prometheus:
    endpoint: "0.0.0.0:8889"
    resource_to_telemetry_conversion:
      enabled: true
  # otlphttp/seq:
  #   endpoint: "http://seq:5341/ingest/otlp"
  #   tls:
  #     insecure: true
  # file:
  #   path: /otel-logs/data.json
  # file/test-out:
  #   rotation:
  #     max_megabytes: 1
  #   path: ./logs/test.json
  #   flush_interval: 1s
  file: 
    path: /data/logs/logging.json
  

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [logging, prometheus]
    logs:
      receivers: [otlp]
      exporters: [logging, file]
     
